In [2]:
import pandas as pd
import numpy as np

In [3]:
data_students = pd.read_csv("students.csv", index_col= None, header=None,sep=";")

In [4]:
students = data_students.values

students = students[0:,:-2]

In [5]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [6]:
mean = np.mean(students[:,-1])

mean

4.430000000000001

In [7]:
median = np.median(students[:,-1])
median

4.449999999999999

In [8]:
median_weight = np.median(students[:,-2])
median_weight

42.0

In [9]:
mean_weight = np.mean(students[:,-2])

mean_weight - median_weight

1.7999999999999972

In [12]:
corr = np.corrcoef(students[:,2],students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [17]:
std = np.std(students[:,2])
std**2

60.36

In [21]:
disp = np.var(students[:,2])
disp

60.36

Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [53]:
bigdata = np.array([x**2 for x in range(100,1001) if x%2 == 1])

bigdata

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [35]:
mean_bg = np.std(bigdata)
mean_bg

292095.0301991155

In [70]:
bg_2 = bigdata[0::2]
bg_1 = bigdata[1::2]

len(bg_1)

coef = np.corrcoef(bg_1,bg_2)
coef


array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])